plugins {
    id 'java'
    id 'application'
    id 'org.openjfx.javafxplugin' version '0.1.0'
}

group = 'scouting'
version = '1.0'

repositories {
    mavenCentral()
}

java {
    toolchain {
        languageVersion = JavaLanguageVersion.of(17)
    }
}

javafx {
    version = '21.0.2'
    modules = ['javafx.controls', 'javafx.fxml', 'javafx.swing']
}

application {
    mainClass = 'scouting.Main'
}

dependencies {
    implementation 'com.google.zxing:core:3.5.3'
    implementation 'com.google.zxing:javase:3.5.3'
    implementation 'com.fazecast:jSerialComm:2.10.4'
    implementation 'com.opencsv:opencsv:5.9'

    testImplementation platform('org.junit:junit-bom:5.10.0')
    testImplementation 'org.junit.jupiter:junit-jupiter'
    implementation 'com.google.code.gson:gson:2.10.1'
    implementation 'com.github.sarxos:webcam-capture:0.3.12'}

test {
    useJUnitPlatform()
}